### ISSUE TITLE
The tool breaks if the config file is empty

### ISSUE THREAD

**Issue by WilliamMcCumstie** [alces-software/flight-account#1]
If the config exists but is empty, it loads as `false` instead of an empty hash. This causes the entire app to break:
```
[~/Documents/flight-account]$ bin/flight-account login --trace

  'o`
 'ooo`                        Alces Flight account management
 `oooo`                                  v1.0.2 -- 2018-05-30
  `oooo`         'o`
    `ooooo`  `ooooo
       `oooo:oooo`
          `v  -[ alces flight ]-

To sign in to your Alces Flight account please enter your username and
password.

Username: (william) %
[~/Documents/flight-account]$ touch ~/.config/flight/accounts/config.yml
[~/Documents/flight-account]$ bin/flight-account login --trace
/home/william/Documents/flight-account/lib/alces/account/config.rb:36:in `auth_token': undefined method `[]' for false:FalseClass (NoMethodError)
        from /home/william/Documents/flight-account/lib/alces/account/commands/account.rb:131:in `login'
        from /usr/share/rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/commander-4.4.5/lib/commander/command.rb:183:in `call'
        from /usr/share/rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/commander-4.4.5/lib/commander/command.rb:153:in `run'
        from /usr/share/rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/commander-4.4.5/lib/commander/runner.rb:446:in `run_active_command'
        from /usr/share/rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/commander-4.4.5/lib/commander/runner.rb:68:in `run!'
        from /usr/share/rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/commander-4.4.5/lib/commander/delegates.rb:15:in `run!'
        from /home/william/Documents/flight-account/lib/alces/account/cli.rb:35:in `run'
        from bin/flight-account:15:in `<main>'
```

**Comment by WilliamMcCumstie** [comment]
This has probably been fixed with the update to `FlightConfig`. To be confirmed
